---
- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
   - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_distribution }}.yml"
   - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
   - "{{ ansible_os_family }}.yml"
   - default.yml

- name: Ensure aide is installed
  yum:
    name: "{{ aide_pkg }}"
    state: latest

- name: Check for existing aide database
  stat:
    path: "{{ aide_dbdir }}/{{ aide_database_filename }}"
  register: aide_db_check
  changed_when: "aide_db_check.stat.exists != True"
  notify:
    - Initialize aide database
    - Move new aide database into place

- name: Configure /etc/aide.conf
  template:
    src: aide.conf.j2
    dest: /etc/aide.conf
    validate: aide -D -c /etc/aide.conf

#Setup crontab
- name: Ensure aide check is setup in crontab - No Email Report
  cron:
    name: "{{ aide_cronjob_name }}"
    backup: yes
    user: root
    state: present
    minute: "{{ aide_cron_sched_min }}"
    hour: "{{ aide_cron_sched_hr }}"
    day: "{{ aide_cron_sched_day }}"
    month: "{{ aide_cron_sched_mon }}"
    weekday: "{{ aide_cron_sched_wkd }}"
    job: "{{ aide_path }} --check"
  when:
    - aide_cron_email_notify == ''
    - aide_cron_schedule_check == True

- name: Ensure aide check is setup in crontab - With Email Report
  cron:
    name: "{{ aide_cronjob_name }}"
    backup: yes
    user: root
    state: present
    minute: "{{ aide_cron_sched_min }}"
    hour: "{{ aide_cron_sched_hr }}"
    day: "{{ aide_cron_sched_day }}"
    month: "{{ aide_cron_sched_mon }}"
    weekday: "{{ aide_cron_sched_wkd }}"
    job: "{{ aide_path }} --check | /usr/bin/mail -s \"AIDE Report - $HOSTNAME\" {{ aide_cron_email_notify }}"
  when:
    - aide_cron_email_notify != ''
    - aide_cron_schedule_check == True

#Remove old cron jobs when aide_cron_schedule_check has been changed to False
- name: Ensure aide check is removed in crontab - No Email Report
  cron:
    name: "{{ aide_cronjob_name }}"
    state: absent
  when:
    - aide_cron_email_notify == ''
    - aide_cron_schedule_check == False

- name: Ensure aide check is removed in crontab - With Email Report
  cron:
    name: "{{ aide_cronjob_name }}"
    state: absent
  when:
    - aide_cron_email_notify != ''
    - aide_cron_schedule_check == False

- name: Update aide database
  shell: aide -u
  register: aide_update
  failed_when: "aide_update.rc > 7"
  when: "aide_db_check.stat.exists == True"
  notify:
    - Move new aide database into place
