---
- name: Ensure aide is installed
  yum: name="{{ aide_pkg }}" state=latest

- name: Check for existing aide database
  stat: path="{{ aide_dbdir }}/{{ aide_database_filename }}"
  register: aide_db_check
  changed_when: "aide_db_check.stat.exists != True"
  notify:
    - Initialize aide database
    - Move new aide database into place

- name: Configure /etc/aide.conf
  template: src=aide.conf.j2 dest=/etc/aide.conf
  register: config 

- name: Validate Aide Configuration
  shell: aide -D -c /etc/aide.conf
  when: config.changed

#Setup crontab
- name: Ensure aide check is setup in crontab - No Email Report
  cron: 
    name: "{{ aide_cronjob_name }}"
    backup: yes 
    user: root 
    state: present 
    minute: "{{ aide_cron_sched_min }}"
    hour: "{{ aide_cron_sched_hr }}"
    day: "{{ aide_cron_sched_day }}"
    month: "{{ aide_cron_sched_mon }}"
    weekday: "{{ aide_cron_sched_wkd }}"
    job: aide --check
  when: (aide_cron_email_notify == '' and aide_cron_schedule_check == True)

- name: Ensure aide check is setup in crontab - With Email Report
  cron:
    name: "{{ aide_cronjob_name }}"
    backup: yes
    user: root
    state: present
    minute: "{{ aide_cron_sched_min }}"
    hour: "{{ aide_cron_sched_hr }}"
    day: "{{ aide_cron_sched_day }}"
    month: "{{ aide_cron_sched_mon }}"
    weekday: "{{ aide_cron_sched_wkd }}"
    job: aide --check | /usr/bin/mail -s "AIDE Report - $HOSTNAME" "{{ aide_cron_email_notify }}"
  when: (aide_cron_email_notify != '' and aide_cron_schedule_check == True)

#Remove old cron jobs when aide_cron_schedule_check has been changed to False
- name: Ensure aide check is removed in crontab - No Email Report
  cron: name="{{ aide_cronjob_name }}" state=absent
  when: (aide_cron_email_notify == '' and aide_cron_schedule_check == False)

- name: Ensure aide check is removed in crontab - With Email Report
  cron: name="{{ aide_cronjob_name }}" state=absent
  when: (aide_cron_email_notify != '' and aide_cron_schedule_check == False)

- name: Update aide database
  shell: aide -u
  register: aide_update
  failed_when: "aide_update.rc > 7"
  when: "aide_db_check.stat.exists == True"
  notify: 
    - Move new aide database into place
